NUM_PHILOSOPHERS = 5
NUM_FORKS = NUM_PHILOSOPHERS

MAX_FRAME_RATE = 5 / 12 --12 frames per second
MAX_SECONDS = 5

STATES = {
   "Thinking",
   "Hungry",
   "Eating",
   "Full"
}

PIXEL_SIZE = 32

TABLE_REAL_HEIGHT = 70
TABLE_HEIGHT = 35
TABLE_WIDTH = 70